spring:
  profiles:
    active: dev
  application:
    name: provider-pay-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://119.3.66.33:9000/eureka

  instance:
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
server:
  port: 1001